feat(our-work): dynamic routing for detail pages
brown-ccv/ccv-website-nuxt pull request #132
Opened 2023-08-15 21:13 UTC by ashleysyg

2023-08-28 13:17 UTC, eldu requested changes
I think this looks good to me. Wondering why we're downgrading the node version in this PR.

Also, since the cards only take up half the page, with the new detail page perhaps we move away from cards and use up the whole page? A the moment, all the descriptions are short so it might be a bit silly, but could still be nice.

2023-08-28 13:17 UTC, eldu commented on .tool-versions
> +nodejs 14.21.0
Why have we downgraded node versions?

2023-09-06 16:09 UTC, hetd54 approved these changes

2023-09-06 16:59 UTC, eldu approved these changes
:tada: amazing work !

2023-09-06 17:30 UTC, merged